lines = [  
\"import jwt from 'jsonwebtoken';\"  
\"\"  
\"const JWT_SECRET = process.env.JWT_SECRET || 'fallback-secret-for-dev-only';\"  
\"\"  
\"export function authenticateToken(req, res, next) {\"  
\"  const authHeader = req.headers['authorization'];\"  
\"  const token = authHeader && authHeader.split(' ')[1];\"  
\"\"  
\"  if (!token) {\"  
\"    return res.status(401).json({ error: 'Unauthorized: Missing token' });\"  
\"  }\"  
\"\"  
\"  jwt.verify(token, JWT_SECRET, (err, user) => {\"  
\"    if (err) {\"  
\"      return res.status(401).json({ error: 'Unauthorized: Invalid token' });\"  
\"    }\"  
\"    req.user = user;\"  
\"    next();\"  
\"  });\"  
\"}\"  
\"\"  
\"export function requireRole(role) {\"  
\"  return (req, res, next) => {\"  
\"    if (!req.user) {\"  
\"      return res.status(401).json({ error: 'Unauthorized: Missing user context' });\"  
\"    }\"  
\"    if (req.user.role !== role) {\"  
\"      return res.status(403).json({ error: 'Forbidden: Requires ' + role + ' role' });\"  
\"    }\"  
\"    next();\"  
\"  };\"  
\"}\"  
\"\"  
\"// Alias for compatibility with routes that may import authorizeRole\"  
\"export const authorizeRole = requireRole;\"  
\"]\"  
\"with open('E:/HACKATHON/backend/middleware/auth.js', 'w') as f:\"  
\"    f.write('\\n'.join(lines))\" 
